const timetableData = {
    "GroundFloorLabs":[
        {
            "title": "AC31012/AC51042 - Information Security",
            "start": 12,
            "end": 14,
            "day": 0,
            "week": [1,2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Sasa Radomirovic"],
        },
        {
            "title": "AC11002 - Web Authoring",
            "start": 14,
            "end": 18,
            "day": 0,
            "week": [1,2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Michael Crabb"],
        },
        {
            "title": "AC32006/52001 - Database Systems",
            "start": 9,
            "end": 11,
            "day": 1,
            "week": [2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Iain Murray"],
        },
        {
            "title": "AC21009 - Computer Systems 2A",
            "start": 11,
            "end": 13,
            "day": 1,
            "week": [2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Iain Murray", "Dr Jianguo Zhang"],
        },
        {
            "title": "AC21011 - Creative Interactions",
            "start": 13,
            "end": 17,
            "day": 1,
            "week": [1,2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Rachel Menzies", "Dr Craig Ramsay"],
        },
        {
            "title": "AC41011/51011 - Big Data",
            "start": 17,
            "end": 18,
            "day": 1,
            "week": [4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Islem Rekik"],
        },

        {
            "title": "AC31008 - Networks and Data Communications",
            "start": 9,
            "end": 11,
            "day": 2,
            "week": [1,2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Michael Crabb"],
        },

        {
            "title": "AC21008 - Multi-Paradigm Programming",
            "start": 9,
            "end": 11,
            "day": 3,
            "week": [1,2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Craig Ramsay", "Dr Sasa Radomirovic"],
        },
        {
            "title": "AC21009 - Computer Systems 2A",
            "start": 12,
            "end": 14,
            "day": 3,
            "week": [2,3,4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Iain Murray", "Dr Jianguo Zhang"],
        },
        {
            "title": "AC11001 - Introduction to Software Development",
            "start": 15,
            "end": 17,
            "day": 3,
            "week": [2,3,4,5,6,7,8,9,10,12],
            "staff": ["Dr Iain Martin"],
        },
        {
            "title": "AC41011/51011 - Big Data",
            "start": 17,
            "end": 18,
            "day": 3,
            "week": [4,5,6,7,8,9,10,11,12],
            "staff": ["Dr Islem Rekik"],
        },

        {
            "title": "AC11001 - Introduction to Software Development",
            "start": 9,
            "end": 10,
            "day": 4,
            "week": [1,2,3,4,5,6,7,8,9,10,11],
            "staff": ["Dr Iain Martin"],
        },

        {
            "title": "AC21012 - Users and Interfaces",
            "start": 10,
            "end": 12,
            "day": 4,
            "week": [1,2,3,4,5,6,7,8,9,10],
            "staff": ["Dr Alison Pease", "Dr Craig Ramsay"],
        },
        {
            "title": "AC21008 - Multi-Paradigm Programming",
            "start": 9,
            "end": 11,
            "day": 4,
            "week": [1,2,3,4,5,6,7,8,9,10],
            "staff": ["Dr Craig Ramsay", "Dr Sasa Radomirovic"],
        },
        {
            "title": "AC11001 - Introduction to Software Development",
            "start": 16,
            "end": 18,
            "day": 4,
            "week": [1,2,3,4,5,6,7,8,9,10,11],
            "staff": ["Dr Iain Martin"],
        },
    ]
}

module.exports = timetableData;